# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d7ae6af30eebc69ee57ccca742bbc865d2eff5db83037556645a23bfa3162550f9cf9d360509232f89c74860120475859bc09abe4ce7e61a453d96da880d155

test:
  secret_key_base: 77d0647f1ce77cca8aac512925bd1c23a8b640cd3c8955c7caa55edac292ad472ca30405e64e9f06158adf21eeff98b3bf82900bccfb8a1c3cccc7a1b8d1f760

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
